// Generated by CoffeeScript 1.12.0

/*
scalableminds\coffeelint-newline-after-function
https://github.com/scalableminds/coffeelint-newline-after-function

Copyright (c) 2014 Tom Herold
Licensed under the MIT license.
 */

(function() {
  module.exports = require("./src/newline_after_function");

}).call(this);
