// Generated by CoffeeScript 1.12.0
(function() {
  var NewlinesAfterFunction;

  module.exports = NewlinesAfterFunction = (function() {
    function NewlinesAfterFunction() {}

    NewlinesAfterFunction.prototype.rule = {
      name: 'newline_after_function',
      value: 1,
      level: 'error',
      message: 'Wrong count of newlines between a function and other code',
      description: "Checks the number of newlines between a function definition and other code"
    };

    NewlinesAfterFunction.prototype.lintLine = function(line, lineApi) {
      var context, i, j, lineNumber, line_spacing, nextLine, ref;
      line_spacing = lineApi.config[this.rule.name].value;
      if (!line_spacing || lineApi.isLastLine()) {
        return null;
      }
      lineNumber = lineApi.lineNumber, context = lineApi.context;
      if (lineApi.lineHasToken("->") || lineApi.lineHasToken("=>")) {
        for (i = j = 1, ref = line_spacing; 1 <= ref ? j <= ref : j >= ref; i = 1 <= ref ? ++j : --j) {
          nextLine = lineNumber + i;
          if (lineApi.lineHasToken(null, nextLine)) {
            return {
              context: "Expected " + line_spacing + " got " + (nextLine - lineNumber - 1)
            };
          }
        }
      }
      return null;
    };

    return NewlinesAfterFunction;

  })();

}).call(this);
